# Generated by Django 5.1.4 on 2025-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='field',
            new_name='email',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'date', 'meal_type')},
        ),
    ]
