# Generated by Django 5.1.4 on 2025-04-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0002_rename_field_user_email_meal_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
