# Generated by Django 5.1.4 on 2025-05-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0003_ingredient_barcode_ingredient_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='user',
        ),
    ]
