# Generated by Django 5.1.4 on 2025-05-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barcode_app", "0004_remove_barcode_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meal",
            unique_together={("user", "date")},
        ),
        migrations.AddField(
            model_name="meal",
            name="emoji",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name="meal",
            name="meal_type",
        ),
    ]
